version: '3.7'

services:
  registry:
    image: registry:2
    ports:
      - "443:443"
    volumes:
      - /mnt/registry:/var/lib/registry
      - /etc/blip/certs:/certs
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.blip.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.blip.key
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s      
      resources:
        limits:
          memory: 50M
